2021-12-28 09:08:08,695 -_test_log.py[line: 44] -INFO:
    --1th log start here ********************
2021-12-28 09:08:08,698 -_test_func.py[line: 4] -INFO:
    --info of test func ------------------------------------------
2021-12-28 09:08:08,699 -_test_func.py[line: 5] -INFO:
    --get input x: 3, y: 2.
2021-12-28 09:08:08,701 -_test_func.py[line: 6] -WARNING:
    --this is a warning.
2021-12-28 09:08:08,702 -_test_func.py[line: 7] -ERROR:
    --some error may find here.
2021-12-28 09:08:08,702 -_test_func.py[line: 9] -DEBUG:
    --x div y : 1.5
2021-12-28 09:08:08,703 -_test_func.py[line: 13] -CRITICAL:
    --program may crash here.
2021-12-28 09:08:08,704 -_test_func.py[line: 14] -INFO:
    --test function finished.
2021-12-28 09:08:08,705 -_test_log.py[line: 46] -INFO:
    --test finished.
2021-12-28 09:08:10,710 -_test_log.py[line: 44] -INFO:
    --2th log start here ********************
2021-12-28 09:08:10,711 -_test_func.py[line: 4] -INFO:
    --info of test func ------------------------------------------
2021-12-28 09:08:10,711 -_test_func.py[line: 5] -INFO:
    --get input x: 3, y: 2.
2021-12-28 09:08:10,712 -_test_func.py[line: 6] -WARNING:
    --this is a warning.
2021-12-28 09:08:10,713 -_test_func.py[line: 7] -ERROR:
    --some error may find here.
2021-12-28 09:08:10,714 -_test_func.py[line: 9] -DEBUG:
    --x div y : 1.5
2021-12-28 09:08:10,714 -_test_func.py[line: 13] -CRITICAL:
    --program may crash here.
2021-12-28 09:08:10,715 -_test_func.py[line: 14] -INFO:
    --test function finished.
2021-12-28 09:08:10,716 -_test_log.py[line: 46] -INFO:
    --test finished.
