2021-12-26 20:19:18,613 -test_log.py[line: 29] -INFO:
    --Log start here *********************************************
2021-12-26 20:19:18,614 -test_func.py[line: 4] -INFO:
    --info of test func ------------------------------------------
2021-12-26 20:19:18,614 -test_func.py[line: 5] -INFO:
    --get input x: 3, y: 1.
2021-12-26 20:19:18,615 -test_func.py[line: 6] -WARNING:
    --this is a warning.
2021-12-26 20:19:18,616 -test_func.py[line: 7] -ERROR:
    --some error may find here.
2021-12-26 20:19:18,617 -test_func.py[line: 9] -DEBUG:
    --x div y : 3.0
2021-12-26 20:19:18,618 -test_func.py[line: 13] -CRITICAL:
    --program may crash here.
2021-12-26 20:19:18,618 -test_func.py[line: 14] -INFO:
    --test function finished.
2021-12-26 20:19:18,619 -test_log.py[line: 31] -INFO:
    --test finished.
