2021-12-26 20:13:51,893 -test_log.py[line: 42] -INFO:
    --1th log start here ********************
2021-12-26 20:13:51,896 -test_func.py[line: 4] -INFO:
    --info of test func ------------------------------------------
2021-12-26 20:13:51,897 -test_func.py[line: 5] -INFO:
    --get input x: 3, y: 2.
2021-12-26 20:13:51,897 -test_func.py[line: 6] -WARNING:
    --this is a warning.
2021-12-26 20:13:51,898 -test_func.py[line: 7] -ERROR:
    --some error may find here.
2021-12-26 20:13:51,899 -test_func.py[line: 9] -DEBUG:
    --x div y : 1.5
2021-12-26 20:13:51,899 -test_func.py[line: 13] -CRITICAL:
    --program may crash here.
2021-12-26 20:13:51,901 -test_func.py[line: 14] -INFO:
    --test function finished.
2021-12-26 20:13:51,901 -test_log.py[line: 44] -INFO:
    --test finished.
2021-12-26 20:13:53,902 -test_log.py[line: 42] -INFO:
    --2th log start here ********************
2021-12-26 20:13:53,903 -test_func.py[line: 4] -INFO:
    --info of test func ------------------------------------------
2021-12-26 20:13:53,903 -test_func.py[line: 5] -INFO:
    --get input x: 3, y: 2.
2021-12-26 20:13:53,904 -test_func.py[line: 6] -WARNING:
    --this is a warning.
2021-12-26 20:13:53,904 -test_func.py[line: 7] -ERROR:
    --some error may find here.
2021-12-26 20:13:53,905 -test_func.py[line: 9] -DEBUG:
    --x div y : 1.5
2021-12-26 20:13:53,906 -test_func.py[line: 13] -CRITICAL:
    --program may crash here.
2021-12-26 20:13:53,908 -test_func.py[line: 14] -INFO:
    --test function finished.
2021-12-26 20:13:53,909 -test_log.py[line: 44] -INFO:
    --test finished.
