2021-12-19 14:18:47,936 -test_log.py[line: 16] -INFO:
    --Log start here *********************************************
2021-12-19 14:18:47,938 -test_func.py[line: 4] -INFO:
    --info of test func ------------------------------------------
2021-12-19 14:18:47,939 -test_func.py[line: 5] -INFO:
    --get input x: 3, y: 5.
2021-12-19 14:18:47,939 -test_func.py[line: 6] -WARNING:
    --this is a warning.
2021-12-19 14:18:47,940 -test_func.py[line: 7] -ERROR:
    --some error may find here.
2021-12-19 14:18:47,941 -test_func.py[line: 9] -DEBUG:
    --x div y : 0.6
2021-12-19 14:18:47,941 -test_func.py[line: 13] -CRITICAL:
    --program may crash here.
2021-12-19 14:18:47,942 -test_func.py[line: 14] -INFO:
    --test function finished.
2021-12-19 14:18:47,943 -test_log.py[line: 18] -INFO:
    --≤‚ ‘Ω· ¯.
